version: 2

project_name: gorm-iotdb

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cli-placeholder
    main: ./examples/crud
    binary: gorm-iotdb-example
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: git

release:
  github:
    owner: wkk778
    name: gorm-iotdb
