version: "3.9"
services:
  iotdb-1-1:
    image: apache/iotdb:1.1.2-standalone
    ports:
      - "6667:6667"
      - "18080:18080"
  iotdb-1-2:
    image: apache/iotdb:1.2.0-standalone
    ports:
      - "6668:6667"
      - "18081:18080"
