name: ci

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.20", "1.21"]
        os: [ubuntu-latest, macos-latest]
        iotdb-version: ["1.1.2", "1.2.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test ./...
      - run: go test ./tests/...
